[package]
name = "feishu_bot"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/feishu_bot.rs"
doctest = false

[dependencies]
anyhow.workspace = true
git.workspace = true
futures.workspace = true
gpui.workspace = true
log.workspace = true
proto.workspace = true
shellexpand.workspace = true
smol.workspace = true
remote_server.workspace = true
project.workspace = true
regex.workspace = true
rpc = { workspace = true, features = ["gpui"] }
serde.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde_json.workspace = true
uuid = { workspace = true, features = ["v4"] }
